# Generated by Django 2.2.3 on 2019-07-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_auto_20190728_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='concentration',
        ),
        migrations.RemoveField(
            model_name='player',
            name='hometown',
        ),
        migrations.RemoveField(
            model_name='player',
            name='image',
        ),
        migrations.RemoveField(
            model_name='player',
            name='internship',
        ),
        migrations.RemoveField(
            model_name='player',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='player',
            name='longterm',
        ),
        migrations.RemoveField(
            model_name='player',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='player',
            name='points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='postgrad',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year',
        ),
    ]
